version: '3.9'

services:
  web:
    build: .
    command: gunicorn streamflix.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    # depends_on:
    #   - db
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - mynetwork

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  mynetwork:
